import os

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY', 'please-change-me-dev')
    BASE_PATH = os.getenv('BASE_PATH', '/app')
    PLATFORM = os.getenv('PLATFORM', 'marktools')
    PLATFORM_VERSION = os.getenv('PLATFORM_VERSION', '1.0.0')
    MTV2_BASE_URL = os.getenv('MTV2_BASE_URL', 'https://api.mtv2.com/v1/')
    MTV2_API_TOKEN = os.getenv('MTV2_API_TOKEN', 'your_default_mtv2_api_token')
    SR_BASE_URL = os.getenv('SR_BASE_URL', 'https://api.srp.agnet.top/')
    SR_API_KEY = os.getenv('SR_API_KEY', 'your_default_srp_api_token')
    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', 'your_default_openai_api_key')
    OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://api.deepseek.com/v1/')
    OPENAI_PROXY_API_KEY = os.getenv('OPENAI_PROXY_API_KEY', 'your_default_openai_proxy_api_key')
    OPENAI_PROXY_BASE_URL = os.getenv('OPENAI_PROXY_BASE_URL', 'https://api.deepseek.com/v1/')
    GROK_API_KEY = os.getenv('GROK_API_KEY', 'your_default_grok_api_key')
    GROK_BASE_URL = os.getenv('GROK_BASE_URL', 'https://api.grok.com/v1/')
    DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', 'your_default_deepseek_api_key')
    DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1/')
    ZHIPUAI_API_KEY = os.getenv('ZHIPUAI_API_KEY', 'your_default_zhipuai_api_key')
    HSFZ_API_KEY = os.getenv('HSFZ_API_KEY', 'your_default_hsfz_api_key')
    HSFZ_BASE_URL = os.getenv('HSFZ_BASE_URL', 'https://api.hsfz.com/v1/')
    GB_API_KEY = os.getenv('GB_API_KEY', 'your_default_gb_api_key')
    GB_BASE_URL = os.getenv('GB_BASE_URL', 'https://gb.agnet.top/openai/v1')
    LONGCAT_API_KEY = os.getenv('LONGCAT_API_KEY', 'your_default_gb_api_key')
    LONGCAT_BASE_URL = os.getenv('LONGCAT_BASE_URL', 'https://api.longcat.chat/openai')
    OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', 'your_default_openrouter_api_key')
    OPENROUTER_BASE_URL = os.getenv('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1/')
    SIMPLE_GOOGLE_API_KEY = os.getenv('SIMPLE_GOOGLE_API_KEY', 'your_default_SIMPLE_GOOGLE_API_KEY')
    GOOGLE_CLOUD_PROJECT = os.getenv('GOOGLE_CLOUD_PROJECT', 'meta-buckeye-433400-c6')
    GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS', 'google_credentials/meta-buckeye-433400-c6-109fbeae7021.json')
    GOOGLE_SEARCH_API_KEY = os.getenv('GOOGLE_SEARCH_API_KEY', 'your_default_google_search_api_key')
    GOOGLE_SEARCH_CX = os.getenv('GOOGLE_SEARCH_CX', 'your_default_google_search_cx')
    BUCKET_NAME = os.getenv('BUCKET_NAME', 'speech-audio-mark')
    LLM_SERVICE = os.getenv('LLM_SERVICE', 'deepseek')
    REDIS_URL = os.getenv('REDIS_URL', 'your_default_redis_url')
    MYSQL = os.getenv('MYSQL', 'your_default_mysql')
    # starbot
    STARBOT_TOKEN = os.getenv('STARBOT_TOKEN', 'your_default_starbot_token')
    STARBOT_API_URL = os.getenv('STARBOT_API_URL', 'your_default_starbot_api_url')
    STARBOT_MAIN_ROBOT_ID = os.getenv('STARBOT_MAIN_ROBOT_ID', 'your_default_starbot_main_robot_id')
    # fas5
    FAS5_TOKEN = os.getenv('FAS5_TOKEN', 'your_default_fas5_token')
    FAS5_API_URL = os.getenv('FAS5_API_URL', 'your_default_fas5_api_url')
